version: '3.3'
services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=planner
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  plan:
    image: vladoap/plan:v1
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
    depends_on:
      db:
        condition: service_healthy

